### ISSUE TITLE
Cards & Forms

### ISSUE THREAD

**Issue by alicaudle** [alicaudle/ecommerce-pattern-library#2]
For my email capture card, I can't get the text to go on top of the image and centred to the right. It seems like my email-capture-css file doesn't work. Do I have enough cards? And for Forms, how many more should I create?
@thomasjbradley

**Comment by alicaudle** [comment]
Also, I don't know why my box for phone number is so long.

**Comment by alicaudle** [comment]
Also, also, where do I put my skip-links? I only ever remember putting them at the top of my body on my main index page but now we have a million different pages for everything so I don't understand where they're supposed to go. @thomasjbradley

**Comment by thomasjbradley** [comment]
*Skip links—* would got into the layouts. Likely default. But you may not have gotten that far.

**Comment by thomasjbradley** [comment]
*Phone card—* The indentation here, doesn’t match the other sections above:
https://github.com/alicaudle/ecommerce-pattern-library/blob/master/_patterns/forms/config.yml#L20-L23

**Comment by thomasjbradley** [comment]
*Do you have enough—* I cannot answer that question. Do you have enough to support every situation on your website? Do you have enough to make a full website—even including the pages we didn’t wireframe?

**Comment by thomasjbradley** [comment]
*Email capture—* You don’t need all this boilerplate. That’s all handled by the pattern library:
https://github.com/alicaudle/ecommerce-pattern-library/blob/master/_patterns/cards/email-capture.html#L1-L10
