### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by alicaudle** [alicaudle/ecommerce-pattern-library#5]
My logo won't show up in my header.
@thomasjbradley

**Comment by thomasjbradley** [comment]
Did you figure this out? I can see the black "juice." logo in your header.

![Screen Shot 2020-06-22 at 2 25 55 PM](https://user-images.githubusercontent.com/105192/85322405-4db3a600-b494-11ea-97d2-66ffd48ab0a6.png)

**Comment by alicaudle** [comment]
lol, yeah, I had something totally unrelated that failed in my code so I had to fix that and THEN all my other stuff started showing up properly :)

**Comment by alicaudle** [comment]
https://github.com/alicaudle/ecommerce-pattern-library/blob/master/_patterns/header/header.html

@thomasjbradley 

I can't figure out how to keep the links pined to the far right while being perfectly aligned with the logo.

**Comment by thomasjbradley** [comment]
I would use Flex box to solve the problem—there are classes in `modules.css` you can use.

- Add these three classes to this line: `.flex-row`, `.flex-justify` & `.flex-align-center`
https://github.com/alicaudle/ecommerce-pattern-library/blob/master/_patterns/header/header.html#L4

Then you can use `.flex-row` on your nav `<ul>` also.

**Comment by alicaudle** [comment]
https://github.com/alicaudle/ecommerce-pattern-library/blob/master/_patterns/footer/footer.html

**Comment by alicaudle** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
Delete these extra CSS files within your patterns, like here:
https://github.com/alicaudle/ecommerce-pattern-library/blob/master/_patterns/footer/footer.html#L1

**Comment by thomasjbradley** [comment]
Then, the broken footer, I think is the `pin-rc` class.
Put the two social icons in the same `<div>` and it should start working properly.
